POST http://localhost:3333/videos
Content-Type: application/json

{
 "title": "Video node",
  "description": "Esse é o dsasads ",
  "duration": "100"
}

###

GET http://localhost:3333/videos

###

PUT http://localhost:3333/videos/90cd1b83-a75d-450c-b158-34eca1d3f2b9
Content-Type: application/json

{
 "title": "Video 02",
  "description": "Esse é o video ",
  "duration": "100"
}
###

DELETE http://localhost:3333/videos/2b92445a-484b-4df4-8634-b780f3de02e5
